name: Pull Request

body:
  - type: textarea
    id: description
    attributes:
      label: Describe your changes
      description: A clear and concise description of your changes
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue ticket number and link
    validations:
      required: true
  - type: markdown
    attributes:
    label: Checklist before requesting a review
      value: | 
      - [ ] I have performed a self-review of my code
      - [ ] My code follows the style guidelines of this project
      - [ ] I have made corresponding changes to the documentation
    validations:
      required: true



