name: Bug Report
description: Report a bug in libocpp

body:
  - type: dropdown
    id: affected-ocpp-version
    attributes:
      label: Which OCPP is affected?
      options:
        - OCPP1.6
        - OCPP2.0.1
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: |
        A clear and concise description of what the bug is. If applicable, add screenshots or logfiles to help explain your problem.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      placeholder: |
        If applicable describe the steps to and additional information to reproduce the behavior like:
          * Message communication between CSMS and ChargePoint
          * Used configuration(s)
          * Your system information

  - type: textarea
    id: other
    attributes:
      label: Anything else?
